---
galaxy_info:
  author: Mikael Gibert
  description: Terraform installation
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all  
  - name: Debian
    versions:
    - all
  categories:
  - cloud
dependencies: []