---

- name: Include keys
  include_vars: ../secrets/ssh_keys.yml

- name: setup private key
  copy:
    content: "{{ ssh_keys.ansible.private }}"
    dest: /home/ansible/.ssh/id_rsa
    owner: ansible
    group: ansible
    mode: 0400
  become: true

- name: get ansible repo
  git:
    repo: 'git@gitlab.com:srkaycg/solitaire/ansible-bot.git'
    dest: /home/ansible/ansible
    force: yes
    accept_hostkey: yes

- name: install supervisor, redis and python-dev
  apt:
    name: "{{ item }}"
  become: true
  with_items:
  - supervisor
  - redis-server
  - python-dev
  - software-properties-common

- name: setup redis
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
  become: true

- name: setup message bridge
  copy:
    src: message_bridge.conf
    dest: /etc/supervisor/conf.d/message_bridge.conf
  become: true

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  become: true

- name: add ansible repository
  command: apt-add-repository -y ppa:ansible/ansible
  become: true

- name: install ansible
  apt:
    name: ansible
    update_cache: yes

