---

- name: get ansible repo
  git:
    repo: 'http://10.0.1.5/ansible-bot'
    dest: /home/ansible/ansible
    force: yes

- name: install supervisor and redis
  apt:
    name: "{{ item }}"
  become: true
  with_items:
  - supervisor
  - redis-server

- name: setup redis
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
  become: true

- name: setup message bridge
  copy:
    src: message_bridge.conf
    dest: /etc/supervisor/conf.d/message_bridge.conf
  become: true

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  become: true

- name: setup private key
  copy:
    content: "{{ ssh_keys.ansible.private }}"
    dest: /home/ansible/.ssh/id_rsa
    owner: ansible
    group: ansible
    mode: 0400
  become: true
