
- name: get expose subnet cidr
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc.vpc_id }}"
      "tag:Name": "{{ item }}"
  with_items:
    - control-01
  register: subnet_facts

- set_fact:
    subnet_ids: "{{ subnet_facts.results|map(attribute='subnets.0.id')|list }}"

- name: security group for ansible
  ec2_group:
    name: ansible
    description: ansible
    vpc_id: "{{ vpc.vpc_id }}"
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.1.1.0/24
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 0.0.0.0/0
  register: group 

- name: Ensure tags are present
  ec2_tag:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    resource: "{{ group.group_id }}"
    state: present
    tags:
      Name: ansible

- name: setup ansible
  ec2:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    key_name: bastion
    instance_type: t2.small
    image: "{{ ami }}"
    wait: no
    exact_count: 1
    group: ansible
    vpc_subnet_id: "{{ subnet_ids[0] }}"
    assign_public_ip: no
    count_tag:
      Name: ansible
    instance_tags:
      Name: ansible
  register: instance

- debug: var=instance

- name: setup DNS record
  route53:
    command: create
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    zone: ip
    private_zone: true
    record: "{{ instance.tagged_instances[0].tags.Name }}.ip"
    type: A
    ttl: 300
    value: "{{ instance.tagged_instances[0].private_ip }}"
    wait: no
    overwrite: true

- name: security group for openldap
  ec2_group:
    name: openldap
    description: openldap
    vpc_id: "{{ vpc.vpc_id }}"
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.1.2.0/24
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.1.3.0/24
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.1.0.0/16
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
  register: group

- name: Ensure tags are present
  ec2_tag:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    resource: "{{ group.group_id }}"
    state: present
    tags:
      Name: openldap

- name: setup openldap
  ec2:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    key_name: ansible
    instance_type: t2.small
    image: "{{ ami }}"
    wait: no
    exact_count: 1
    group: openldap
    vpc_subnet_id: "{{ subnet_ids[0] }}"
    assign_public_ip: no
    count_tag:
      Name: openldap
    instance_tags:
      Name: openldap
  register: instance

- name: setup DNS record
  route53:
    command: create
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    zone: ip
    private_zone: true
    record: "{{ instance.tagged_instances[0].tags.Name }}.ip"
    type: A
    ttl: 300
    value: "{{ instance.tagged_instances[0].private_ip }}"
    wait: no
    overwrite: true

- name: security group for jenkins
  ec2_group:
    name: jenkins
    description: jenkins
    vpc_id: "{{ vpc.vpc_id }}"
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.1.2.0/24
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.1.3.0/24
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.1.2.0/24
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.1.3.0/24
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
  register: group

- name: Ensure tags are present
  ec2_tag:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    resource: "{{ group.group_id }}"
    state: present
    tags:
      Name: jenkins

- name: setup jenkins
  ec2:
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    region: "{{ region }}"
    key_name: ansible
    instance_type: t2.medium
    image: "{{ ami }}"
    wait: no
    exact_count: 1
    group: jenkins
    vpc_subnet_id: "{{ subnet_ids[0] }}"
    assign_public_ip: no
    count_tag:
      Name: jenkins
    instance_tags:
      Name: jenkins
  register: instance

- name: setup DNS record
  route53:
    command: create
    aws_access_key: "{{ aws.ansible.key }}"
    aws_secret_key: "{{ aws.ansible.secret }}"
    zone: ip
    private_zone: true
    record: "{{ instance.tagged_instances[0].tags.Name }}.ip"
    type: A
    ttl: 300
    value: "{{ instance.tagged_instances[0].private_ip }}"
    wait: no
    overwrite: true
