---
- name: ensure supervisor
  apt:
    name: supervisor
  become: true

- name: install flask
  pip:
    name: flask

- name: copy the server script
  template:
    src: check_my_ip_server.py
    dest: /home/ubuntu/check_my_ip_server.py
    mode: 0555

- name: copy supervisor config
  template:
    src: check_my_ip_super_config.conf
    dest: /etc/supervisor/conf.d/check_my_ip_super_config.conf
  become: true

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
