---
# Redquired creds
- name: Include docker registry credentials
  include_vars: ../secrets/docker_registry_creds.yml

- name: Include required credentials
  include_vars: ../secrets/common.yml

- name: login into docker registry
  when: docker_registry_login 
  command: "docker login -u {{ docker_registry_user }} -p {{ docker_registry_pass }} {{ docker_registry_name }}"

- name: get available services
  command: docker service list
  register: docker_services

- name: removing the service
  command: "docker service rm {{ service_env }}-{{ service }}"
  when: reset_service == '1' and "{{ service_env }}-{{ service }}" in docker_services.stdout
  ignore_errors: yes

- name: get available services
  command: docker service list
  register: docker_services

- name: get docker command
  set_fact:
    docker_command: "{{ lookup('template', 'docker_command.j2') }}"

- name: deploying using
  debug: var=docker_command

- name: deploying the service
  command: "{{ docker_command }}"

- name: use proper loadbalancer ip
  set_fact:
    lb_ip: "{{ internal_lb_ip }}"
  when: 'prod' != service_env

- name: use proper loadbalancer ip
  set_fact:
    lb_ip: "{{ prod_lb_ip }}"
  when: 'prod' == service_env

- name: setup the service url
  command: "{{ lookup('template', 'subdomain_api_call.j2') }}"
