---

- name: removing the service
  command: "docker service rm {{ service_env }}-{{ service }}"
  when: reset_service

- name: get available services
  command: docker service list
  register: docker_services

- name: get docker command
  set_fact:
    docker_command: "{{ lookup('template', 'docker_command.j2') }}"

- name: deploying using
  debug: var=docker_command

- name: deploying the service
  command: "{{ docker_command }}"
