---
# Redquired creds
- name: Include docker registry credentials
  include_vars: ../secrets/docker_registry_creds.yml

- name: Include required credentials
  include_vars: ../secrets/common.yml

- name: login into docker registry
  when: docker_registry_login 
  shell: "$(aws ecr get-login --region us-east-2)"

- name: get available services
  command: docker service list
  register: docker_services

- name: removing the service
  command: "docker service rm {{ service_env }}-{{ service }}"
  when: reset_service == '1' and "{{ service_env }}-{{ service }}" in docker_services.stdout
  ignore_errors: yes

- name: get available services
  command: docker service list
  register: docker_services

- name: get docker command
  set_fact:
    docker_command: "{{ lookup('template', 'docker_command.j2') }}"

- name: deploying using
  debug: var=docker_command

- name: deploying the service
  command: "{{ docker_command }}"

