---

- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "Common-default.yml"
      paths: vars

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: configure.yml

- include: setup-bridge.yml

- name: setup firewall rules
  template:
    src: firewall_rules
    dest: /tmp/firewall_rules
    mode: 0700

- name: apply firewall rules
  command: /tmp/firewall_rules

- name: Ensure OpenVPN is started
  service: name={{openvpn_service}} state=started enabled=yes

- name: for restart on xenial
  command: systemctl restart openvpn@server.service
