---
# handlers file for openvpn

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  tags:
    - openvpn

- name: restart openvpn
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: restarted
  tags:
    - openvpn
