---

- hosts: swarm-01
  tasks:
    - shell: "docker pull {{ image }}:{{ git_commit }}"
    - shell: "docker service create --network {{ network }} --mode {{ replication_mode }} --replicas {{ replicas }} --name {{ service_env }}-{{ service }} --publish {{ port }}:{{ port }} --with-registry-auth {{ image }}:{{ git_commit }}"
      ignore_errors: yes
      when: replication_mode == 'replicated'

    - shell: "docker service create --network {{ network }} --mode {{ replication_mode }} --name {{ service_env }}-{{ service }} --publish {{ port }}:{{ port }} --with-registry-auth {{ image }}:{{ git_commit }}"
      ignore_errors: yes
      when: replication_mode == 'global'

    - shell: "docker service update --image {{ image }}:{{ git_commit }} --replicas {{ replicas }} --with-registry-auth {{ service_env }}-{{ service }}"
