- name: "Provision Docker Swarm Cluster"
  hosts: docker_engine
  become: true
  roles:
    - { role: setup_dockerswarm }
    - { role: setup_weavescope }
    - { role: setup_fluentd }
    - { role: setup_check_my_ip_server }
    - { role: setup_docker_haproxy }
