---

- name: include keys
  include_vars: ../secrets/ssh_keys.yml

- name: Install python-software-properties
  apt:
    name: python-software-properties
    state: installed
    update_cache: yes
  become: true

- name: Install python-pycurl
  apt: name=python-pycurl state=installed
  become: true

- name: Add jenkins apt-key
  apt_key: data="{{ lookup('file', 'jenkins-ci.org.key') }}" state=present
  become: true

- name: Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present update_cache=yes
  become: true

- name: install jenkins
  apt:
    name: jenkins
    update_cache: yes
  become: true

- name: setup private key
  copy:
    content: "{{ ssh_keys.jenkins.private }}"
    dest: ~/.ssh/id_rsa
  become: jenkins

- name: init jenkins repo
  command: "cd /var/lib/jenkins && git init && git remote set-url origin git@gitlab.com:srkaycg/solitaire/jenkins.git"
  become: jenkins

- name: check service
  service:
    name: jenkins
    status: restarted

- name: setup nginx proxy
  apt:
    name: nginx
    update_cache: yes

- name: configure nginx proxy
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
  become: true

- name: restart proxy
  service:
    name: nginx
    status: restarted
